<?php

/** @var $block \OpenTechiz\Blog\Block\PostList */ ?>
<h1><?= __('Latest Blog Posts') ?></h1>
<ul class="blog-post-list">
    <?php /** @var $post \OpenTechiz\Blog\Model\Post */ ?>
    <?php foreach ($block->getPosts() as $post) : ?>
        <li class="blog-post-list-item">
            <h3 class="blog-post-item-title">
                <a href="<?= $post->getUrl() ?>"><?= $post->getTitle() ?></a>
            </h3>

            <div class="blog-post-item-content">
                <?= $post->getContent() ?>
            </div>

            <div class="blog-post-item-meta">
                <strong><?= __('Created at') ?></strong><?= $post->getCreationTime() ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>